### PR TITLE
Added navbar

### PR DESCRIPTION
**Pull request by HimangsKalita**

### CODE REVIEW

**Comment by helper-uttam** [comment]
Hey @HimangsKalita ! thankyou so much for your contribution.
I'll merge it for sure :) but let me confirm first why it's not being counted in `hacktoberfest21`
Kudos to your first contributions 😍😍🤩

**Comment by HimangsKalita** [comment]
@helper-uttam Thanks you for the opportunity learned something new

**Comment by HimangsKalita** [comment]
Yea I am registered for hacktoberfest

**Comment by helper-uttam** [comment]
> Yea I am registered for hacktoberfest

great! let me know whether your count of valid PR increased or not?

**Comment by HimangsKalita** [comment]
> > Yea I am registered for hacktoberfest
> 
> great! let me know whether your count of valid PR increased or not?

No, it's showing the project is not participating for Hacktoberfest
image

**Comment by helper-uttam** [comment]
> > > Yea I am registered for hacktoberfest
> > 
> > 
> > great! let me know whether your count of valid PR increased or not?
> 
> No, it's showing the project is not participating for Hacktoberfest image

Please Pardon! :(
See some other projects on GitHub that are participating in hacktoberfest, something gone wrong with this repository , i apologize :(

**Comment by HimangsKalita** [comment]
> > > > Yea I am registered for hacktoberfest
> > > 
> > > 
> > > great! let me know whether your count of valid PR increased or not?
> > 
> > No, it's showing the project is not participating for Hacktoberfest image
> 
> Please Pardon! :(
> See some other projects on GitHub that are participating in hacktoberfest, something gone wrong with this repository , i apologize :(

No worries

**Pull request merged**
